spring:
 mvc:
  view.prefix: /WEB-INF/jsp/
  view.suffix: .jsp
 aop:
   auto: true
 profiles:
   active: local

spring.application.name: spring-boot-test
spring.sleuth.web.skipPattern: "/ok"
spring.mvc.async.request-timeout: "90000"

server:
  port: 9443
  servlet:
    context-path: /cisco
  ssl:
   enabled: true
   key-store: local.keystore
   key-store-password: local.keystore

msg.sender: weixin

---
spring.profiles: local
enable.local.debug: true
consul:
  datacenter: alln-stg
server:
  port: 9000
  ssl:
   enabled: false
#eureka:
#  client:
#    service-url:
#      #注册中心的访问地址。
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    #是否将当前服务的 IP 注册到 Eureka Server
#    prefer-ip-address: true

