spring:
 mvc:
  view.prefix: /WEB-INF/jsp/
  view.suffix: .jsp
 aop:
   auto: true
# datasource:
#    url: jdbc:mysql://sjc-coi01-lnx:3306/ulm?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
 profiles:
   active: local

spring.application.name: spring-boot-test
spring.sleuth.web.skipPattern: "/ok"
spring.mvc.async.request-timeout: "90000"

msg.sender: weixin

---
spring.profiles: local
enable.local.debug: true
consul:
  datacenter: alln-stg
server:
  port: 9000
  ssl:
   enabled: false